### ISSUE TITLE
Pessing `q` in the GPT buffer exits vim

### ISSUE THREAD

**Issue by sbmueller** [kamou/gpt-vim#1]
Hi, with several buffers open and one of them being the GPT Log, when pressing `q` in the GPT buffer, vim exits cleanly. Expectation would be that only the GPT buffer is closed.
Any idea what could be the problem?
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

```

**Comment by kamou** [comment]
should be fixed now :)

**Comment by kamou** [comment]
you can reopen the issue if the issue persists.
