### ISSUE TITLE
Issue updating database to v2

### ISSUE THREAD

**Issue by sbmueller** [kamou/gpt-vim#2]
Hi there,

With the newest commits on master, when I invoke the chat window with `gpa`, I get this error:
```
10:57:05 msg_show Updating conversation database to v2
   Error  10:57:05 msg_show.rpc_error Error detected while processing function gpt#Assist[4]..gpt#chat#register[40]..gpt#chat#Prepare[3]..provider#python3#Call:
10:57:05 msg_show line   18:
10:57:05 msg_show >  Error invoking 'python_eval' on channel 3 (python3-script-host):
error caught in request handler 'python_eval ["gpt.check_and_update_db(vim.eval('g:gpt#plugin_dir'))"]':
Traceback (most recent call last):
  File "/path/to/home/.local/lib/python3.8/site-packages/pynvim/plugin/script_host.py", line 167, in python_eval
    return eval(expr, self.module.__dict__)
  File "<string>", line 1, in <module>
  File "/path/to/home/.local/share/nvim/plugged/gpt-vim/python3/gpt.py", line 345, in check_and_update_db
    conversations = extract_conversations_v1(path)
  File "/path/to/home/.local/share/nvim/plugged/gpt-vim/python3/gpt.py", line 385, in extract_conversations_v1
    cursor.execute(f"SELECT * FROM {table_name}")
sqlite3.OperationalError: no such table: conversations
```

Any idea what's wrong?

**Comment by kamou** [comment]
seems like the db was empty (or at least the conversations table is missing), but thats' weird because it shouldn't.

try to list the tables with the following command:
```
$ sqlite3 ~/.gpt-vim/history/history.db .tables
```

if it's empty, just remove the database.
I can update the code to check for the presence of the table. but it should be there.

**Comment by sbmueller** [comment]
Without looking too much into the code, I reckon the table is only created when this function is called:
https://github.com/kamou/gpt-vim/blob/master/python3/gpt.py#L290

Which never happens implicitly, I think.

**Comment by kamou** [comment]
oh right, fixed

**Comment by kamou** [comment]
there is still a problem, let me have a look

**Comment by kamou** [comment]
now it's fixed

**Comment by kamou** [comment]
oops, I forgot to commit the database, now it's really fixed 😅
